// <auto-generated />
using System;
using CaptchaVerificationSystem.Persistence.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CaptchaVerificationSystem.Persistance.Migrations
{
    [DbContext(typeof(CaptchaDbContext))]
    partial class CaptchaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CaptchaVerificationSystem.Domain.Entities.CaptchaAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AttemptedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CaptchaChallengeId")
                        .HasColumnType("uuid");

                    b.Property<int>("CorrectSelectionCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MissedCorrectCount")
                        .HasColumnType("integer");

                    b.Property<int>("ResponseTimeMs")
                        .HasColumnType("integer");

                    b.Property<int>("Result")
                        .HasColumnType("integer");

                    b.Property<int>("RiskLevel")
                        .HasColumnType("integer");

                    b.Property<decimal>("Score")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("WrongSelectionCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CaptchaChallengeId");

                    b.ToTable("CaptchaAttempts");
                });

            modelBuilder.Entity("CaptchaVerificationSystem.Domain.Entities.CaptchaAttemptSelection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CaptchaAttemptId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CaptchaChallengeImageId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsCorrectSelection")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSelected")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CaptchaAttemptId");

                    b.HasIndex("CaptchaChallengeImageId");

                    b.ToTable("CaptchaAttemptSelections");
                });

            modelBuilder.Entity("CaptchaVerificationSystem.Domain.Entities.CaptchaChallenge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsSolved")
                        .HasColumnType("boolean");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TargetCategoryId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TargetCategoryId");

                    b.ToTable("CaptchaChallenges");
                });

            modelBuilder.Entity("CaptchaVerificationSystem.Domain.Entities.CaptchaChallengeImage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CaptchaChallengeId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ImageId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CaptchaChallengeId");

                    b.HasIndex("ImageId");

                    b.ToTable("CaptchaChallengeImages");
                });

            modelBuilder.Entity("CaptchaVerificationSystem.Domain.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("CaptchaVerificationSystem.Domain.Entities.Image", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Height")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Width")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Images");
                });

            modelBuilder.Entity("CaptchaVerificationSystem.Domain.Entities.ImageCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ImageId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ImageId");

                    b.ToTable("ImageCategories");
                });

            modelBuilder.Entity("CaptchaVerificationSystem.Domain.Entities.CaptchaAttempt", b =>
                {
                    b.HasOne("CaptchaVerificationSystem.Domain.Entities.CaptchaChallenge", "CaptchaChallenge")
                        .WithMany("CaptchaAttempts")
                        .HasForeignKey("CaptchaChallengeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CaptchaChallenge");
                });

            modelBuilder.Entity("CaptchaVerificationSystem.Domain.Entities.CaptchaAttemptSelection", b =>
                {
                    b.HasOne("CaptchaVerificationSystem.Domain.Entities.CaptchaAttempt", "CaptchaAttempt")
                        .WithMany("CaptchaAttemptSelections")
                        .HasForeignKey("CaptchaAttemptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CaptchaVerificationSystem.Domain.Entities.CaptchaChallengeImage", "CaptchaChallengeImage")
                        .WithMany("CaptchaAttemptSelections")
                        .HasForeignKey("CaptchaChallengeImageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CaptchaAttempt");

                    b.Navigation("CaptchaChallengeImage");
                });

            modelBuilder.Entity("CaptchaVerificationSystem.Domain.Entities.CaptchaChallenge", b =>
                {
                    b.HasOne("CaptchaVerificationSystem.Domain.Entities.Category", "TargetCategory")
                        .WithMany("CaptchaChallenges")
                        .HasForeignKey("TargetCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TargetCategory");
                });

            modelBuilder.Entity("CaptchaVerificationSystem.Domain.Entities.CaptchaChallengeImage", b =>
                {
                    b.HasOne("CaptchaVerificationSystem.Domain.Entities.CaptchaChallenge", "CaptchaChallenge")
                        .WithMany("CaptchaChallengeImages")
                        .HasForeignKey("CaptchaChallengeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CaptchaVerificationSystem.Domain.Entities.Image", null)
                        .WithMany("CaptchaChallengeImages")
                        .HasForeignKey("ImageId");

                    b.Navigation("CaptchaChallenge");
                });

            modelBuilder.Entity("CaptchaVerificationSystem.Domain.Entities.ImageCategory", b =>
                {
                    b.HasOne("CaptchaVerificationSystem.Domain.Entities.Category", "Category")
                        .WithMany("ImageCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CaptchaVerificationSystem.Domain.Entities.Image", "Image")
                        .WithMany("ImageCategories")
                        .HasForeignKey("ImageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Image");
                });

            modelBuilder.Entity("CaptchaVerificationSystem.Domain.Entities.CaptchaAttempt", b =>
                {
                    b.Navigation("CaptchaAttemptSelections");
                });

            modelBuilder.Entity("CaptchaVerificationSystem.Domain.Entities.CaptchaChallenge", b =>
                {
                    b.Navigation("CaptchaAttempts");

                    b.Navigation("CaptchaChallengeImages");
                });

            modelBuilder.Entity("CaptchaVerificationSystem.Domain.Entities.CaptchaChallengeImage", b =>
                {
                    b.Navigation("CaptchaAttemptSelections");
                });

            modelBuilder.Entity("CaptchaVerificationSystem.Domain.Entities.Category", b =>
                {
                    b.Navigation("CaptchaChallenges");

                    b.Navigation("ImageCategories");
                });

            modelBuilder.Entity("CaptchaVerificationSystem.Domain.Entities.Image", b =>
                {
                    b.Navigation("CaptchaChallengeImages");

                    b.Navigation("ImageCategories");
                });
#pragma warning restore 612, 618
        }
    }
}
